"""create model factura

Revision ID: 19f32740dc8b
Revises: 80cb853f4ef5
Create Date: 2026-07-30 17:43:02.984098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19f32740dc8b'
down_revision: Union[str, Sequence[str], None] = '80cb853f4ef5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('veterinaria_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('codigo_factura', sa.String(length=30), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('descuento', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('observaciones', sa.String(length=1000), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['veterinaria_id'], ['veterinarias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('veterinaria_id', 'numero', name='uq_factura_numero_veterinaria')
    )
    op.create_index(op.f('ix_facturas_codigo_factura'), 'facturas', ['codigo_factura'], unique=False)
    op.create_index(op.f('ix_facturas_id'), 'facturas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_facturas_id'), table_name='facturas')
    op.drop_index(op.f('ix_facturas_codigo_factura'), table_name='facturas')
    op.drop_table('facturas')
    # ### end Alembic commands ###
