"""initial schema

Revision ID: 2326736663fc
Revises: 
Create Date: 2026-07-20 17:40:43.669949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2326736663fc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('veterinarias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_veterinarias_id'), 'veterinarias', ['id'], unique=False)
    op.create_index(op.f('ix_veterinarias_slug'), 'veterinarias', ['slug'], unique=True)
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('veterinaria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['veterinaria_id'], ['veterinarias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('rol', sa.Enum('ADMIN', 'VETERINARIO', 'RECEPCIONISTA', name='rolusuario'), nullable=False),
    sa.Column('foto_url', sa.String(length=500), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('veterinaria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['veterinaria_id'], ['veterinarias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', 'veterinaria_id', name='uq_usuario_email_veterinaria'),
    sa.UniqueConstraint('google_id')
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('mascotas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('especie', sa.String(length=50), nullable=False),
    sa.Column('raza', sa.String(length=100), nullable=True),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('veterinaria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['veterinaria_id'], ['veterinarias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mascotas_id'), 'mascotas', ['id'], unique=False)
    op.create_table('turnos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'CONFIRMADO', 'ATENDIDO', 'CANCELADO', name='estadoturno'), nullable=False),
    sa.Column('mascota_id', sa.Integer(), nullable=False),
    sa.Column('veterinaria_id', sa.Integer(), nullable=False),
    sa.Column('observaciones', sa.String(length=1000), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mascota_id'], ['mascotas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['veterinaria_id'], ['veterinarias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_turnos_id'), 'turnos', ['id'], unique=False)
    op.create_index('ix_turnos_veterinaria_fecha', 'turnos', ['veterinaria_id', 'fecha_hora'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_turnos_veterinaria_fecha', table_name='turnos')
    op.drop_index(op.f('ix_turnos_id'), table_name='turnos')
    op.drop_table('turnos')
    op.drop_index(op.f('ix_mascotas_id'), table_name='mascotas')
    op.drop_table('mascotas')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_veterinarias_slug'), table_name='veterinarias')
    op.drop_index(op.f('ix_veterinarias_id'), table_name='veterinarias')
    op.drop_table('veterinarias')
    # ### end Alembic commands ###
