"""modificar usuario con roles y sus relaciones

Revision ID: 31a0816a230e
Revises: 7e701e9f2ab1
Create Date: 2026-07-16 19:53:04.629125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31a0816a230e'
down_revision: Union[str, Sequence[str], None] = '7e701e9f2ab1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mascotas', sa.Column('veterinaria_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'mascotas', 'veterinarias', ['veterinaria_id'], ['id'])
    op.add_column('turnos', sa.Column('usuario_id', sa.Integer(), nullable=False))
    op.add_column('turnos', sa.Column('veterinaria_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'turnos', 'usuarios', ['usuario_id'], ['id'])
    op.create_foreign_key(None, 'turnos', 'veterinarias', ['veterinaria_id'], ['id'])
    op.add_column('usuarios', sa.Column('apellido', sa.String(length=100), nullable=False))
    op.add_column('usuarios', sa.Column('telefono', sa.String(length=30), nullable=True))
    op.add_column('usuarios', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('usuarios', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('usuarios', sa.Column('rol', sa.Enum('ADMIN', 'VETERINARIO', 'RECEPCIONISTA', name='rolusuario'), nullable=False))
    op.drop_constraint(op.f('usuarios_email_key'), 'usuarios', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('usuarios_email_key'), 'usuarios', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('usuarios', 'rol')
    op.drop_column('usuarios', 'updated_at')
    op.drop_column('usuarios', 'created_at')
    op.drop_column('usuarios', 'telefono')
    op.drop_column('usuarios', 'apellido')
    op.drop_constraint(None, 'turnos', type_='foreignkey')
    op.drop_constraint(None, 'turnos', type_='foreignkey')
    op.drop_column('turnos', 'veterinaria_id')
    op.drop_column('turnos', 'usuario_id')
    op.drop_constraint(None, 'mascotas', type_='foreignkey')
    op.drop_column('mascotas', 'veterinaria_id')
    # ### end Alembic commands ###
