"""create turnos table

Revision ID: 7e701e9f2ab1
Revises: 3177c1416344
Create Date: 2026-07-14 21:22:18.949747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e701e9f2ab1'
down_revision: Union[str, Sequence[str], None] = '3177c1416344'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('turnos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('mascota_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mascota_id'], ['mascotas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_turnos_id'), 'turnos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_turnos_id'), table_name='turnos')
    op.drop_table('turnos')
    # ### end Alembic commands ###
