"""create adjuntos table

Revision ID: 80cb853f4ef5
Revises: 60589c2d267a
Create Date: 2026-07-28 20:25:21.793426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80cb853f4ef5'
down_revision: Union[str, Sequence[str], None] = '60589c2d267a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adjuntos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('historia_clinica_id', sa.Integer(), nullable=False),
    sa.Column('estudio_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('veterinaria_id', sa.Integer(), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=255), nullable=False),
    sa.Column('ruta_archivo', sa.String(length=500), nullable=False),
    sa.Column('tipo_archivo', sa.String(length=100), nullable=False),
    sa.Column('tamano', sa.BigInteger(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['estudio_id'], ['estudios.id'], ),
    sa.ForeignKeyConstraint(['historia_clinica_id'], ['historias_clinicas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['veterinaria_id'], ['veterinarias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adjuntos_id'), 'adjuntos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_adjuntos_id'), table_name='adjuntos')
    op.drop_table('adjuntos')
    # ### end Alembic commands ###
