"""create cajas and movimientos_caja tables and relationship

Revision ID: 9fcdae3e3e55
Revises: cba840b39e9e
Create Date: 2026-08-01 09:54:15.939903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fcdae3e3e55'
down_revision: Union[str, Sequence[str], None] = 'cba840b39e9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cajas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('veterinaria_id', sa.Integer(), nullable=False),
    sa.Column('usuario_apertura_id', sa.Integer(), nullable=False),
    sa.Column('usuario_cierre_id', sa.Integer(), nullable=True),
    sa.Column('saldo_inicial', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('saldo_final', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fecha_apertura', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_cierre', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estado', sa.Enum('ABIERTA', 'CERRADA', name='estadocaja'), nullable=False),
    sa.Column('observaciones', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['usuario_apertura_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['usuario_cierre_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['veterinaria_id'], ['veterinarias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cajas_id'), 'cajas', ['id'], unique=False)
    op.create_table('movimientos_caja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caja_id', sa.Integer(), nullable=False),
    sa.Column('veterinaria_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('factura_id', sa.Integer(), nullable=True),
    sa.Column('pago_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('INGRESO', 'EGRESO', name='tipomovimientocaja'), nullable=False),
    sa.Column('origen', sa.Enum('PAGO', 'GASTO', 'AJUSTE', name='origenmovimientocaja'), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['caja_id'], ['cajas.id'], ),
    sa.ForeignKeyConstraint(['factura_id'], ['facturas.id'], ),
    sa.ForeignKeyConstraint(['pago_id'], ['pagos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['veterinaria_id'], ['veterinarias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimientos_caja_id'), 'movimientos_caja', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movimientos_caja_id'), table_name='movimientos_caja')
    op.drop_table('movimientos_caja')
    op.drop_index(op.f('ix_cajas_id'), table_name='cajas')
    op.drop_table('cajas')
    # ### end Alembic commands ###
