"""create recetas, recetas_medicamentos tables

Revision ID: fac41c16eb15
Revises: 0f229937cbf6
Create Date: 2026-07-25 12:21:49.069722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fac41c16eb15'
down_revision: Union[str, Sequence[str], None] = '0f229937cbf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recetas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('historia_clinica_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('veterinaria_id', sa.Integer(), nullable=False),
    sa.Column('indicaciones_generales', sa.String(length=1000), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['historia_clinica_id'], ['historias_clinicas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['veterinaria_id'], ['veterinarias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recetas_id'), 'recetas', ['id'], unique=False)
    op.create_table('receta_medicamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receta_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('presentacion', sa.String(length=100), nullable=True),
    sa.Column('dosis', sa.String(length=100), nullable=False),
    sa.Column('frecuencia', sa.String(length=100), nullable=False),
    sa.Column('duracion', sa.String(length=100), nullable=False),
    sa.Column('via_administracion', sa.Enum('ORAL', 'INYECTABLE', 'TOPICA', 'OFTALMICA', 'OTICA', 'NASAL', 'RECTAL', 'OTRA', name='viaadministracion'), nullable=False),
    sa.Column('observaciones', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['receta_id'], ['recetas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receta_medicamentos_id'), 'receta_medicamentos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receta_medicamentos_id'), table_name='receta_medicamentos')
    op.drop_table('receta_medicamentos')
    op.drop_index(op.f('ix_recetas_id'), table_name='recetas')
    op.drop_table('recetas')
    # ### end Alembic commands ###
